### ISSUE TITLE
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

### ISSUE THREAD

**Issue by Kostahe** [Toiletman007/Minecraft-FishBot#3]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

_Originally posted by @Toiletman007 in https://github.com/Toiletman007/Minecraft-FishBot/issues/2#issuecomment-2159388848_
            Fakt dement

**Comment by Toiletman007** [comment]
To snad ne

**Comment by Kostahe** [comment]
@****
